version: "3"
services:
  postgres:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dkflbr
      - POSTGRES_DB=store_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/postgres-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5400:5432"

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["poetry", "run", "python", "./app.py"]